name: Data Embalses Portugal

on:
  schedule:
    - cron: "59 23 * * 1"
  push:

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Catch Data Embalses Portugal
        run: node datosEmbalsesPt.js
