name: Data Embalses 2025

on:
  schedule:
    - cron: "0 2 */2 * *"
  push:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Catch Data 2025
        run: node Embalses2025.js
