name: AcuaNet Cron Jobs
on:
  schedule:
    - cron: "0 6,8,10,12,14,16,18,20,22,0 * * *"
    #- cron: "0 8,14 * * *"
  # push:
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Get pnpm store directory
        shell: bash
        run: |
          STORE_PATH=$(pnpm store path --silent)
          echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install --with-deps
      - run: pnpm node SahiTajo.js
      - run: pnpm node SahiGuadiana.js
      - run: pnpm node SahiEbro.js
      - run: pnpm node SahiGuadalquivir.js
      - run: pnpm node SahiDuero.js
      - run: pnpm node SahiSegura.js
      - run: pnpm node SahiAndaluciaInterna.js
