name: Data AcuaEs

on:
  schedule:
    - cron: "0 */2 * * *"
  push:
jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Catch Data Pluviometros
        run: node pluvis.js

      - name: Catch Data Embalses
        run: node datosEmbalses.js
