name: Data Embalses

on:
  schedule:
    - cron: "0 0 */2 * *"
  push:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Catch Data Embalses
        run: node datosEmbalses.js
