name: Run Node.js script on schedule and push

on:
  schedule:
    - cron: "*/1 * * * *"
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Run script
        run: node pluvis.js && node datosEmbalses.js