name: Run Node.js script every 12 hours

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Run script
        run: node pluvis.js && node datosEmbalses.js